apiVersion: v1
kind: Pod
metadata:
  namespace: testing
  name: nginx
  labels:
      app: web-server
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http
